name: docker

on: [push, pull_request]

jobs:
  build_docker:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        config: [native, aarch64_be-unknown-linux-gnu, arm-unknown-eabi]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Build CIF
      run: make archive/${{ matrix.config }}

    - name: Upload CIF
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.config }}-cif
        path: "*.tar.xz"
